### ISSUE TITLE
Nonces tree dont corresponds to vtxoTree

### ISSUE THREAD

**Issue by sekulicd** [ark-network/ark#361]
This is related to the issue mentioned in [here](https://github.com/ark-network/ark/issues/360).
Code silently panicking in [here](https://github.com/ark-network/ark/blob/bcb2b2075f908ca6102de6788c0d7eeddcdde28a/common/bitcointree/musig2.go#L412) as it looks like tree of nonces doesnt corresponds(for some tree’s i,j index there is not relevant i,j index of nonce tree)to congestionTree(vtxoTree).
Issue can be reproduced by running [simulation](https://github.com/ark-network/ark/pull/358) with bellow config:

```
version: "1.0"

server:
  network: "regtest"
  initial_funding: 1.0
  round_interval: 20

clients:
  - id: "client_0"
    initial_funding: 0.1
  - id: "client_1"
    name: "Client1"
  - id: "client_2"
    name: "Client2"
  - id: "client_3"
    name: "Client3"
  - id: "client_4"
    name: "Client4"
  - id: "client_5"
    name: "Client5"

rounds:
  - number: 1
    actions:
      client_0:
        - type: "Onboard"
          amount: 0.1
  - number: 2
    actions:
      client_0:
        - type: "SendAsync"
          amount: 0.002
          to: "client_1"
        - type: "SendAsync"
          amount: 0.002
          to: "client_2"
        - type: "SendAsync"
          amount: 0.002
          to: "client_3"
        - type: "SendAsync"
          amount: 0.002
          to: "client_4"
        - type: "SendAsync"
          amount: 0.002
          to: "client_5"

  - number: 3
    actions:
      client_1:
        - type: "Claim"
      client_2:
        - type: "Claim"
      client_3:
        - type: "Claim"
      client_4:
        - type: "Claim"
      client_5:
        - type: "Claim"
```
