### ISSUE TITLE
stack overflow on v0.5.0

### ISSUE THREAD

**Issue by johnnyasantoss** [ark-network/ark#488]
Hello,
I've just tried the latest version (0.5.0) and it seems to have a stackoverflow bug.

Here's the debug log of the container.
[0-5-0-logs.txt](https://github.com/user-attachments/files/19011549/0-5-0-logs.txt)

I'm using the following env vars from Polar on my branch to add Ark to it (https://github.com/johnnyasantoss/polar/tree/feature/arkd)
```yaml
      ARK_NETWORK: regtest
      ARK_TX_BUILDER_TYPE: covenantless
      ARK_ROUND_INTERVAL: '5'
      ARK_MIN_RELAY_FEE: '200'
      ARK_LOG_LEVEL: '10'
      ARK_ESPLORA_URL: ''
      ARK_NEUTRINO_PEER: ''
      ARK_BITCOIND_RPC_USER: polaruser
      ARK_BITCOIND_RPC_PASS: polarpass
      ARK_DATADIR: /root/.arkd/data
      ARK_WALLET_DATADIR: /root/.arkd/wallet
      ARK_PORT: '7070'
      ARK_NO_MACAROONS: 'true'
      ARK_NO_TLS: 'true'
      ARK_UNLOCKER_TYPE: env
      ARK_UNLOCKER_PASSWORD: arkpass
      ARK_NOTE_URI_PREFIX: 'Ark on Polar: '
      ARK_NOSTR_DEFAULT_RELAYS: <snip>
      ARK_BITCOIND_RPC_HOST: polar-n2-backend1:18443
```
